{{- if .Values.appconfigs.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploy.name }}-config
  namespace: {{ .Values.namespace }}
data: 
  {{- .Values.configValues | nindent 2 -}}
{{- end }}

