apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
{{- if .Values.configmap.enabled }}
        envFrom:
        - configMapRef:
            name: {{ .Values.envFrom.configMapRef.name }}
{{- end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        serviceAccount: {{ .Values.serviceAccountName }}
        serviceAccountName: {{ .Values.serviceAccountName }}
        env:
          {{- range .Values.env }}       
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }} 
{{- if .Values.resources.enabled }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu}}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
{{- end }}
        ports:
        - containerPort: {{ .Values.svc.containerPort }}