apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
{{- if .Values.configmapEnabled.enabled }}
        envFrom:
        - configMapRef:
            name: {{ .Values.envFrom.configMapRef.name }}
{{- end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
{{- if .Values.resourcesEnabled.enabled }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu}}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
{{- end }}
{{- if .Values.probeEnabled.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probe.pathreadiness }}
            port: {{ .Values.probe.port }}  
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probe.pathliveness }}
            port: {{ .Values.probe.port }} 
          failureThreshold: {{ .Values.probe.failureThreshold }}
          periodSeconds: {{ .Values.probe.periodSeconds }}
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
{{- end }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}