{{- if .Values.svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deploy.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.deploy.targetport }}
  type: NodePort
{{- end }}
